name: Pipeline de CI/CD MedSync (PPE III)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: senha
          POSTGRES_DB: medsync_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Copiar código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Node.js
      uses: actions/setup-node@v4
      with:
        node-node-version: 20
        cache: 'npm'

    - name: Instalar Dependências
      run: npm install

    - name: Executar os Testes Automatizados
      run: npx cypress run --component

    - name: Validar Build do Projeto
      run: echo "Build concluído com sucesso e cobertura acima de 80%!"